COMPLETED      = 81 82 83
CXX            = g++
CXXFLAGS       = -Wall -Wextra -std=c++0x -O3

all: ${COMPLETED}

80 : 80.cc
	${CXX} ${CXXFLAGS} 80.cc -o 80
81 : 81.cc
	${CXX} ${CXXFLAGS} 81.cc -o 81
82 : 82.cc
	${CXX} ${CXXFLAGS} 82.cc -o 82
83 : 83.cc
	${CXX} ${CXXFLAGS} 83.cc -o 83
84 : 84.cc
	${CXX} ${CXXFLAGS} 84.cc -o 84
85 : 85.cc
	${CXX} ${CXXFLAGS} 85.cc -o 85
86 : 86.cc
	${CXX} ${CXXFLAGS} 86.cc -o 86
87 : 87.cc
	${CXX} ${CXXFLAGS} 87.cc -o 87
88 : 88.cc
	${CXX} ${CXXFLAGS} 88.cc -o 88
89 : 89.cc
	${CXX} ${CXXFLAGS} 89.cc -o 89
clean : 
	rm -f 80 81 82 83 84 85 86 87 88 89
