COMPLETED      = 50 52 53 55 56 58 59
CXX            = g++
CXXFLAGS       = -Wall -Wextra -std=c++0x -O3

all: ${COMPLETED}
50 : 50.cc
	${CXX} ${CXXFLAGS} -lcln 50.cc -o 50
51 : 51.cc
	${CXX} ${CXXFLAGS} 51.cc -o 51
52 : 52.cc
	${CXX} ${CXXFLAGS} -lcln 52.cc -o 52
53 : 53.cc
	${CXX} ${CXXFLAGS} -lcln 53.cc -o 53
54 : 54.cc
	${CXX} ${CXXFLAGS} 54.cc -o 54
55 : 55.cc
	${CXX} ${CXXFLAGS} -lcln 55.cc -o 55
56 : 56.cc
	${CXX} ${CXXFLAGS} -lcln 56.cc -o 56
57 : 57.cc
	${CXX} ${CXXFLAGS} 57.cc -o 57
58 : 58.cc
	${CXX} ${CXXFLAGS} 58.cc -o 58
59 : 59.cc
	${CXX} ${CXXFLAGS} 59.cc -o 59
clean : 
	rm -f 50 51 52 53 54 55 56 57 58 59
