COMPLETED = 1 2 3 4 5 6 7 8 9 10
CXX       = g++
CXXFLAGS  = -Wall -Wextra -std=c++0x -O3

all: ${COMPLETED}

1 : 1.cc
	${CXX} ${CXXFLAGS} 1.cc -o 1
2 : 2.cc
	${CXX} ${CXXFLAGS} 2.cc -o 2
3 : 3.cc
	${CXX} ${CXXFLAGS} 3.cc -o 3
4 : 4.cc
	${CXX} ${CXXFLAGS} 4.cc -o 4
5 : 5.cc
	${CXX} ${CXXFLAGS} 5.cc -o 5
6 : 6.cc
	${CXX} ${CXXFLAGS} 6.cc -o 6
7 : 7.cc
	${CXX} ${CXXFLAGS} 7.cc -o 7
8 : 8.cc
	${CXX} ${CXXFLAGS} 8.cc -o 8
9 : 9.cc
	${CXX} ${CXXFLAGS} 9.cc -o 9
10 : 10.cc
	${CXX} ${CXXFLAGS} 10.cc -o 10
