COMPLETED = 11 12 13 14 15 16 17 18 19 20
CXX       = g++
CXXFLAGS  = -Wall -Wextra -std=c++0x -O3

all: ${COMPLETED}

11 : 11.cc
	${CXX} ${CXXFLAGS} 11.cc -o 11
12 : 12.cc
	${CXX} ${CXXFLAGS} 12.cc -o 12
13 : 13.cc
	${CXX} ${CXXFLAGS} -lcln 13.cc -o 13
14 : 14.cc
	${CXX} ${CXXFLAGS} 14.cc -o 14
15 : 15.cc
	${CXX} ${CXXFLAGS} -lcln 15.cc -o 15
16 : 16.cc
	${CXX} ${CXXFLAGS} -lcln 16.cc -o 16
17 : 17.cc
	${CXX} ${CXXFLAGS} 17.cc -o 17
18 : 18.cc
	${CXX} ${CXXFLAGS} 18.cc -o 18
19 : 19.cc
	${CXX} ${CXXFLAGS} 19.cc -o 19
20 : 20.cc
	${CXX} ${CXXFLAGS} -lcln 20.cc -o 20
