COMPLETED      = 52 53 55 56
CXX            = g++
CXXFLAGS       = -Wall -Wextra -std=c++0x -O3
COMMON         = -lcln ../common/Common.cc ../common/Prime.cc

all: ${COMPLETED}

51 : 51.cc
	${CXX} ${CXXFLAGS} 51.cc -o 51
52 : 52.cc
	${CXX} ${CXXFLAGS} ${COMMON} 52.cc -o 52
53 : 53.cc
	${CXX} ${CXXFLAGS} -lcln 53.cc -o 53
54 : 54.cc
	${CXX} ${CXXFLAGS} 54.cc -o 54
55 : 55.cc
	${CXX} ${CXXFLAGS} ${COMMON} 55.cc -o 55
56 : 56.cc
	${CXX} ${CXXFLAGS} ${COMMON} 56.cc -o 56
57 : 57.cc
	${CXX} ${CXXFLAGS} 57.cc -o 57
58 : 58.cc
	${CXX} ${CXXFLAGS} 58.cc -o 58
59 : 59.cc
	${CXX} ${CXXFLAGS} 59.cc -o 59
60 : 60.cc
	${CXX} ${CXXFLAGS} 60.cc -o 60
