COMPLETED      = 92 
CXX            = g++
CXXFLAGS       = -Wall -Wextra -std=c++0x -O4
COMMONSOURCES = ../common/Common.cc ../common/Prime.cc

all: ${COMPLETED}

90 : 90.cc
	${CXX} ${CXXFLAGS} 90.cc -o 90
91 : 91.cc
	${CXX} ${CXXFLAGS} 91.cc -o 91
92 : 92.cc
	${CXX} ${CXXFLAGS} 92.cc -o 92
93 : 93.cc
	${CXX} ${CXXFLAGS} 93.cc -o 93
94 : 94.cc
	${CXX} ${CXXFLAGS} 94.cc -o 94
95 : 95.cc
	${CXX} ${CXXFLAGS} 95.cc -o 95
96 : 96.cc
	${CXX} ${CXXFLAGS} 96.cc -o 96
97 : 97.cc
	${CXX} ${CXXFLAGS} 97.cc -o 97
98 : 98.cc
	${CXX} ${CXXFLAGS} 98.cc -o 98
99 : 99.cc
	${CXX} ${CXXFLAGS} 99.cc -o 99
clean : 
	rm -f 90 91 92 93 94 95 96 97 98 99
