COMPLETED      = 40 41 42 43 44 45 46 47 48 49
CXX            = g++
CXXFLAGS       = -Wall -Wextra -std=c++0x -O3
COMMON         = -lcln ../common/Common.cc ../common/Prime.cc

all: ${COMPLETED}
40 : 40.cc
	${CXX} ${CXXFLAGS} 40.cc -o 40
41 : 41.cc
	${CXX} ${CXXFLAGS} 41.cc -o 41
42 : 42.cc
	${CXX} ${CXXFLAGS} 42.cc -o 42
43 : 43.cc
	${CXX} ${CXXFLAGS} 43.cc -o 43
44 : 44.cc
	${CXX} ${CXXFLAGS} 44.cc -o 44
45 : 45.cc
	${CXX} ${CXXFLAGS} 45.cc -o 45
46 : 46.cc
	${CXX} ${CXXFLAGS} 46.cc -o 46
47 : 47.cc
	${CXX} ${CXXFLAGS} 47.cc -o 47
48 : 48.cc
	${CXX} ${CXXFLAGS} -lcln 48.cc -o 48
49 : 49.cc
	${CXX} ${CXXFLAGS} -lcln 49.cc -o 49
clean :
	rm -f 40 41 42 43 44 45 46 47 48 49
