COMPLETED = 21 22 23 24 25
CXX       = g++
CXXFLAGS  = -Wall -Wextra -std=c++0x -O3

all: ${COMPLETED}

21 : 21.cc
	${CXX} ${CXXFLAGS} 21.cc -o 21
22 : 22.cc
	${CXX} ${CXXFLAGS} 22.cc -o 22
23 : 23.cc
	${CXX} ${CXXFLAGS} 23.cc -o 23
24 : 24.cc
	${CXX} ${CXXFLAGS} 24.cc -o 24
25 : 25.cc
	${CXX} ${CXXFLAGS} -lcln 25.cc -o 25
26 : 26.cc
	${CXX} ${CXXFLAGS} 26.cc -o 26
27 : 27.cc
	${CXX} ${CXXFLAGS} 27.cc -o 27
28 : 28.cc
	${CXX} ${CXXFLAGS} 28.cc -o 28
29 : 29.cc
	${CXX} ${CXXFLAGS} 29.cc -o 29
30 : 30.cc
	${CXX} ${CXXFLAGS} 30.cc -o 30
