COMPLETED      = 76 79
CXX            = g++
CXXFLAGS       = -Wall -Wextra -std=c++0x -O3
COMMON         = -lcln ../common/Common.cc ../common/Prime.cc

all: ${COMPLETED}

70 : 70.cc
	${CXX} ${CXXFLAGS} 70.cc -o 70
71 : 71.cc
	${CXX} ${CXXFLAGS} 71.cc -o 71
72 : 72.cc
	${CXX} ${CXXFLAGS} 72.cc -o 72
73 : 73.cc
	${CXX} ${CXXFLAGS} 73.cc -o 73
74 : 74.cc
	${CXX} ${CXXFLAGS} 74.cc -o 74
75 : 75.cc
	${CXX} ${CXXFLAGS} 75.cc -o 75
76 : 76.cc
	${CXX} ${CXXFLAGS} 76.cc -o 76
77 : 77.cc
	${CXX} ${CXXFLAGS} 77.cc -o 77
78 : 78.cc
	${CXX} ${CXXFLAGS} 78.cc -o 78
79 : 79.cc
	${CXX} ${CXXFLAGS} 79.cc -o 79
clean : 
	rm -f 70 71 72 73 74 75 76 77 78 79
