COMPLETED      = 67 
CXX            = g++
CXXFLAGS       = -Wall -Wextra -std=c++0x -O3
COMMON         = -lcln ../common/Common.cc ../common/Prime.cc

all: ${COMPLETED}

60 : 60.cc
	${CXX} ${CXXFLAGS} 60.cc -o 60
61 : 61.cc
	${CXX} ${CXXFLAGS} 61.cc -o 61
62 : 62.cc
	${CXX} ${CXXFLAGS} 62.cc -o 62
63 : 63.cc
	${CXX} ${CXXFLAGS} 63.cc -o 63
64 : 64.cc
	${CXX} ${CXXFLAGS} 64.cc -o 64
65 : 65.cc
	${CXX} ${CXXFLAGS} 65.cc -o 65
66 : 66.cc
	${CXX} ${CXXFLAGS} 66.cc -o 66
67 : 67.cc
	${CXX} ${CXXFLAGS} 67.cc -o 67
68 : 68.cc
	${CXX} ${CXXFLAGS} 68.cc -o 68
69 : 69.cc
	${CXX} ${CXXFLAGS} 69.cc -o 69
clean : 
	rm -f 60 61 62 63 64 65 66 67 68 69
