COMPLETED = 31 32 33 34 36 37 39 40
CXX       = g++
CXXFLAGS  = -Wall -Wextra -std=c++0x -O3

all: ${COMPLETED}

31 : 31.cc
	${CXX} ${CXXFLAGS} 31.cc -o 31
32 : 32.cc
	${CXX} ${CXXFLAGS} 32.cc -o 32
33 : 33.cc
	${CXX} ${CXXFLAGS} 33.cc -o 33
34 : 34.cc
	${CXX} ${CXXFLAGS} 34.cc -o 34
35 : 35.cc
	${CXX} ${CXXFLAGS} 35.cc -o 35
36 : 36.cc
	${CXX} ${CXXFLAGS} 36.cc -o 36
37 : 37.cc
	${CXX} ${CXXFLAGS} 37.cc -o 37
38 : 38.cc
	${CXX} ${CXXFLAGS} 38.cc -o 38
39 : 39.cc
	${CXX} ${CXXFLAGS} 39.cc -o 39
40 : 40.cc
	${CXX} ${CXXFLAGS} 40.cc -o 40
